In [285]:
#importing required libraries

import tensorflow as tf
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')


In [286]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression 

In [287]:
df=pd.read_csv('train.csv',",")
df.head()

v.id  on road old  on road now  years      km  rating  condition  economy  \
0     1       535651       798186      3   78945       1          2       14   
1     2       591911       861056      6  117220       5          9        9   
2     3       686990       770762      2  132538       2          8       15   
3     4       573999       722381      4  101065       4          3       11   
4     5       691388       811335      6   61559       3          9       12   

   top speed  hp  torque  current price  
0        177  73     123       351318.0  
1        148  74      95       285001.5  
2        181  53      97       215386.0  
3        197  54     116       244295.5  
4        160  53     105       531114.5

In [288]:
tensor_data=tf.constant(df,dtype=tf.float32)
tensor_data

<tf.Tensor: shape=(1000, 12), dtype=float32, numpy=
array([[1.000000e+00, 5.356510e+05, 7.981860e+05, ..., 7.300000e+01,
        1.230000e+02, 3.513180e+05],
       [2.000000e+00, 5.919110e+05, 8.610560e+05, ..., 7.400000e+01,
        9.500000e+01, 2.850015e+05],
       [3.000000e+00, 6.869900e+05, 7.707620e+05, ..., 5.300000e+01,
        9.700000e+01, 2.153860e+05],
       ...,
       [9.980000e+02, 6.463440e+05, 8.427330e+05, ..., 1.130000e+02,
        8.900000e+01, 4.058710e+05],
       [9.990000e+02, 5.355590e+05, 7.324390e+05, ..., 1.120000e+02,
        1.280000e+02, 7.439800e+04],
       [1.000000e+03, 5.901050e+05, 7.797430e+05, ..., 9.900000e+01,
        9.600000e+01, 4.149385e+05]], dtype=float32)>

In [289]:
tensor_data=tf.random.shuffle(tensor_data)

In [290]:
print(tensor_data[:5])

tf.Tensor(
[[8.320000e+02 5.804190e+05 7.308260e+05 3.000000e+00 8.839600e+04
  3.000000e+00 1.000000e+01 1.500000e+01 1.760000e+02 7.700000e+01
  8.200000e+01 3.523185e+05]
 [2.540000e+02 5.214470e+05 7.245110e+05 2.000000e+00 1.144050e+05
  5.000000e+00 3.000000e+00 1.400000e+01 1.790000e+02 6.300000e+01
  7.100000e+01 1.672815e+05]
 [3.690000e+02 5.224010e+05 7.574540e+05 4.000000e+00 6.829400e+04
  5.000000e+00 4.000000e+00 1.000000e+01 1.630000e+02 6.500000e+01
  8.900000e+01 3.685225e+05]
 [2.210000e+02 6.332270e+05 8.381440e+05 7.000000e+00 5.578900e+04
  3.000000e+00 7.000000e+00 1.100000e+01 1.620000e+02 8.100000e+01
  1.050000e+02 5.128855e+05]
 [5.430000e+02 5.160900e+05 8.941130e+05 4.000000e+00 5.456200e+04
  1.000000e+00 3.000000e+00 1.100000e+01 1.450000e+02 9.000000e+01
  1.150000e+02 4.866990e+05]], shape=(5, 12), dtype=float32)


In [291]:
x=tensor_data[:,3:-1]
y=tensor_data[:,-1]

In [292]:
print(x[:5])

tf.Tensor(
[[3.00000e+00 8.83960e+04 3.00000e+00 1.00000e+01 1.50000e+01 1.76000e+02
  7.70000e+01 8.20000e+01]
 [2.00000e+00 1.14405e+05 5.00000e+00 3.00000e+00 1.40000e+01 1.79000e+02
  6.30000e+01 7.10000e+01]
 [4.00000e+00 6.82940e+04 5.00000e+00 4.00000e+00 1.00000e+01 1.63000e+02
  6.50000e+01 8.90000e+01]
 [7.00000e+00 5.57890e+04 3.00000e+00 7.00000e+00 1.10000e+01 1.62000e+02
  8.10000e+01 1.05000e+02]
 [4.00000e+00 5.45620e+04 1.00000e+00 3.00000e+00 1.10000e+01 1.45000e+02
  9.00000e+01 1.15000e+02]], shape=(5, 8), dtype=float32)


In [293]:
y=tf.expand_dims(y,axis=-1)
y.shape
print(y[:5])

tf.Tensor(
[[352318.5]
 [167281.5]
 [368522.5]
 [512885.5]
 [486699. ]], shape=(5, 1), dtype=float32)


In [294]:
from tensorflow.keras.layers import Normalization
normalizer=Normalization()

In [295]:
x.shape

TensorShape([1000, 8])

In [296]:
normalizer=Normalization()
normalizer.adapt(x)
normalizer(x)[:5]

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[-0.90849864, -0.40769094,  0.00855854,  1.561439  ,  1.5138369 ,
         0.4723855 , -0.36797792, -1.0178076 ],
       [-1.4904964 ,  0.48498824,  1.4350005 , -0.9181604 ,  1.0652925 ,
         0.6279974 , -1.0506823 , -1.540418  ],
       [-0.32650092, -1.0976305 ,  1.4350005 , -0.56393194, -0.72888505,
        -0.20193262, -0.95315313, -0.6852374 ],
       [ 1.4194922 , -1.5268263 ,  0.00855854,  0.49875355, -0.28034067,
        -0.25380325, -0.17291953,  0.07492313],
       [-0.32650092, -1.5689393 , -1.4178835 , -0.9181604 , -0.28034067,
        -1.1356039 ,  0.26596186,  0.55002344]], dtype=float32)>

In [297]:
print(x[:5])

tf.Tensor(
[[3.00000e+00 8.83960e+04 3.00000e+00 1.00000e+01 1.50000e+01 1.76000e+02
  7.70000e+01 8.20000e+01]
 [2.00000e+00 1.14405e+05 5.00000e+00 3.00000e+00 1.40000e+01 1.79000e+02
  6.30000e+01 7.10000e+01]
 [4.00000e+00 6.82940e+04 5.00000e+00 4.00000e+00 1.00000e+01 1.63000e+02
  6.50000e+01 8.90000e+01]
 [7.00000e+00 5.57890e+04 3.00000e+00 7.00000e+00 1.10000e+01 1.62000e+02
  8.10000e+01 1.05000e+02]
 [4.00000e+00 5.45620e+04 1.00000e+00 3.00000e+00 1.10000e+01 1.45000e+02
  9.00000e+01 1.15000e+02]], shape=(5, 8), dtype=float32)
